name: ci

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: spearssoftware-k8s
    steps:
      - uses: actions/checkout@v4
      - name: Test ARC
        run: |
          echo "ARC basic test passed"
          uname -a
          date
          whoami
          pwd
